### ISSUE TITLE
Errors encountered while running the example （double free or corruption (out) Aborted (core dumped)）

### ISSUE THREAD

**Issue by LIN-FZ** [mjtq-slamlearning/SI-VSLAM#1]
Thank you for your work and guidance video! I have successfully completed all the previous steps until the last step: Run the Program. I run sh no_ Both ros.sh and sh run.sh will encounter this error.

double free or corruption (out)
Aborted (core dumped)

Look forward to your reply!

**Comment by LIN-FZ** [comment]
Can you provide the versions of various libraries you have installed? For example, opencv, eigen, and so on.

**Comment by GSORF** [comment]
> Can you provide the versions of various libraries you have installed? For example, opencv, eigen, and so on.

Hello @lin-fangzhou,

Thank you for your interest in the project and sorry for my late reply.
Unfortunately, I am very busy with my current work and therefore cannot offer any support for SI-VSLAM at this moment.

Hope you understand my situation.

Kind regards,
Adam
